// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CityDto.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 城市实体
type City struct {
	CityId               int32    `protobuf:"varint,1,opt,name=cityId,proto3" json:"cityId,omitempty"`
	CityName             string   `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_CityDto_0e4ac5550a57c850, []int{0}
}
func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (dst *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(dst, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *City) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func init() {
	proto.RegisterType((*City)(nil), "main.City")
}

func init() { proto.RegisterFile("CityDto.proto", fileDescriptor_CityDto_0e4ac5550a57c850) }

var fileDescriptor_CityDto_0e4ac5550a57c850 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x75, 0xce, 0x2c, 0xa9,
	0x74, 0x29, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0xb2, 0xe2, 0x62, 0x01, 0x09, 0x0b, 0x89, 0x71, 0xb1, 0x25, 0x67, 0x96, 0x54, 0x7a, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42, 0x52, 0x5c, 0x1c, 0x20, 0x96, 0x5f, 0x62,
	0x6e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x9f, 0xc4, 0x06, 0x36, 0xc8, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x0b, 0x4c, 0x3c, 0x59, 0x00, 0x00, 0x00,
}
